db:
  image: postgres:9.5
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD:
  ports:
    - '5432:5432'
  volumes:
    - app-postgres:/var/lib/postgresql/data

app:
  build: .
  links:
    - db
  volumes:
    - .:/app
  ports:
    - '3000:3000'
  env_file:
    - .app.env
