version: '2'
services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - '5432:5432'
    volumes:
      - ./docker/pg:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    env_file:
      - .app.env
    volumes_from:
      - bundle

  bundle:
    image: busybox
    volumes:
      - ./docker/bundle:/bundle

volumes:
  app-postgres: {}
